import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#f1baa7',
        'primary-container': '#071d31',
        'on-primary-fixed-variant': '#35485e',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'on-surface-variant': '#43474d',
        'surface-container-highest': '#e0e3e6',
        background: '#eef2f9',
        'surface-tint': '#4d6077',
        'on-surface': '#191c1e',
        'surface-container': '#eceef1',
        primary: '#000000',
        'on-tertiary-fixed': '#301308',
        'on-error': '#ffffff',
        'surface-bright': '#eef2f9',
        'inverse-surface': '#2d3133',
        outline: '#74777d',
        'error-container': '#ffdad6',
        surface: '#eef2f9',
        'surface-variant': '#e0e3e6',
        'outline-variant': '#c4c6cd',
        'on-tertiary-container': '#a87967',
        'on-secondary-container': '#fefcff',
        'on-primary-container': '#9fafbf',
        'on-error-container': '#93000a',
        'surface-container-low': '#f2f4f7',
        'on-background': '#191c1e',
        'inverse-on-surface': '#eff1f4',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#633d2f',
        'surface-container-high': '#e6e8eb',
        'tertiary-fixed': '#ffdbce',
        'tertiary-container': '#301308',
        'surface-dim': '#d8dadd',
        secondary: '#015396',
        'secondary-hover': '#003c70',
        'surface-container-lowest': '#ffffff',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-padding': '32px',
        gutter: '24px',
        'row-height': '52px',
        'sidebar-width': '260px',
        'toolbar-height': '64px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'body-md': ['Inter'],
        'nav-item': ['Inter'],
        'body-sm': ['Inter'],
        'label-caps': ['Inter'],
        'headline-lg': ['Inter'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'nav-item': ['14px', { lineHeight: '24px', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [forms],
};
