export type View =
  | 'dashboard'
  | 'clients'
  | 'doctors'
  | 'health-companies'
  | 'products'
  | 'quotes'
  | 'settings'
  | 'employees'
  | 'work-orders'
  | 'client-detail'
  | 'client-orthopedic'
  | 'doctor-detail'
  | 'health-company-detail'
  | 'product-detail';
